name: fest_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_xlsio: ^29.1.38
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cupertino_icons: ^1.0.2
  animate_do: ^3.1.2
  cloud_firestore: ^5.6.3
  qr_flutter: ^4.1.0
  intl: ^0.18.0
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  http: ^1.3.0
  url_launcher: ^6.2.4
  file_picker: ^8.0.0
  csv: ^5.0.0
  barcode_scan2: ^4.5.1
  path_provider: ^2.1.2
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Indian_Institute_of_Technology_Ropar_logo.png
    - assets/background.png
    - assets/clock.png
    - assets/light-1.png
    - assets/light-2.png
    - assets/basketball.jpg
    - assets/campus_map.jpg
    - assets/iitrpr.jpeg
    - assets/zeitgeist.jpeg
    - assets/advitiya.jpeg
    - assets/aarohan.jpg
    - assets/sponsor.jpeg
    - assets/sponsor_2.jpeg
    - assets/sponsor_3.jpg
    - assets/night_iitrpr.jpg
    - assets/Default.jpeg
    - assets/Basketball.jpeg
    - assets/basketball.jpg
    - assets/Star Night.jpeg
    - assets/Volleyball.jpeg
    - assets/DJ Night.jpeg
    - assets/Cricket.jpeg
    - assets/Coding.jpeg
    - assets/Software.jpeg
    - assets/Dance.jpeg
    - assets/template.pdf
    - assets/Robotics.jpeg
    - assets/Sports.jpeg
    - assets/Music.jpeg
    - assets/Soccer.jpeg
    - assets/Athletics.jpeg
    - assets/iitropar11.jpg
